### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by ChangJoo-Park** [HaxeFlixel/flixel#1863]
- **Haxe** : 3.3.0
- **Flixel** : 4.0.1
- **iOS**

Hello, I try to build empty haxeflixel template on iOS simulator.
I did not change any files, only run simulator 
What is **Error: Could not find build target "by"** ?
________________________________

**Code snippet reproducing the issue**:
```
➜  ios-test haxelib run lime test ios -simulator
Build settings from command line:
    ARCHS = i386
    PLATFORM_NAME = iphonesimulator
    SDKROOT = iphonesimulator9.3

=== BUILD LEGACY TARGET Build Haxe OF PROJECT ios-test WITH CONFIGURATION Release ===

Check dependencies

ExternalBuildToolExecution Build\ Haxe
    cd /Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/ios-test/haxe
    export ACTION=
    export ALTERNATE_GROUP=staff
    export ALTERNATE_MODE=u+w,go-w,a+rX
    export ALTERNATE_OWNER=changjoopark
    export ALWAYS_SEARCH_USER_PATHS=NO
    export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY=NO
    export APPLY_RULES_IN_COPY_FILES=NO
    export ARCHS=i386
    export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
    export BITCODE_GENERATION_MODE=marker
    export BUILD_ACTIVE_RESOURCES_ONLY=NO
    export BUILD_COMPONENTS="headers build"
    export BUILD_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build
    export BUILD_ROOT=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build
    export BUILD_STYLE=
    export BUILD_VARIANTS=normal
    export BUILT_PRODUCTS_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/Release-iphonesimulator
    export CACHE_ROOT=/var/folders/y5/t02hbcbx1zb5jxtjksg082200000gn/C/com.apple.DeveloperTools/7.3.1-7D1014/Xcode
    export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x
    export CLANG_ENABLE_OBJC_ARC=YES
    export CLANG_MODULES_BUILD_SESSION_FILE=/var/folders/y5/t02hbcbx1zb5jxtjksg082200000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation
    export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
    export CLASS_FILE_DIR="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build/JavaClasses"
    export CLONE_HEADERS=NO
    export CODE_SIGNING_ALLOWED=NO
    export COLOR_DIAGNOSTICS=YES
    export CONFIGURATION=Release
    export CONFIGURATION_BUILD_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/Release-iphonesimulator
    export CONFIGURATION_TEMP_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator
    export COPYING_PRESERVES_HFS_DATA=NO
    export COPY_HEADERS_RUN_UNIFDEF=NO
    export COPY_PHASE_STRIP=YES
    export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
    export DEAD_CODE_STRIPPING=NO
    export DEBUGGING_SYMBOLS=YES
    export DEBUG_INFORMATION_FORMAT=dwarf-with-dsym
    export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
    export DEFINES_MODULE=NO
    export DEPLOYMENT_LOCATION=NO
    export DEPLOYMENT_POSTPROCESSING=NO
    export DERIVED_FILES_DIR=
    export DERIVED_FILE_DIR="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build/DerivedSources"
    export DERIVED_SOURCES_DIR="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build/DerivedSources"
    export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE=English
    export DO_HEADER_SCANNING_IN_JAM=NO
    export DSTROOT=/tmp/ios-test.dst
    export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME=.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
    export DWARF_DSYM_FOLDER_PATH=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/Release-iphonesimulator
    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
    export ENABLE_BITCODE=NO
    export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
    export ENABLE_HEADER_DEPENDENCIES=YES
    export ENABLE_ON_DEMAND_RESOURCES=NO
    export ENABLE_TESTABILITY=NO
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
    export FILE_LIST="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build/Objects/LinkFileList"
    export FRAMEWORK_VERSION=A
    export GCC3_VERSION=3.3
    export GCC_C_LANGUAGE_STANDARD=gnu99
    export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
    export GCC_WARN_ABOUT_RETURN_TYPE=YES
    export GCC_WARN_UNINITIALIZED_AUTOS=YES
    export GCC_WARN_UNUSED_VARIABLE=YES
    export GENERATE_MASTER_OBJECT_FILE=NO
    export GENERATE_PKGINFO_FILE=NO
    export GENERATE_PROFILING_CODE=NO
    export GID=20
    export GROUP=staff
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
    export HEADERMAP_USES_VFS=NO
    export HIDE_BITCODE_SYMBOLS=YES
    export HOME=/Users/changjoopark
    export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
    export INFOPLIST_OUTPUT_FORMAT=binary
    export INFOPLIST_PREPROCESS=NO
    export INSTALL_DIR=/tmp/ios-test.dst
    export INSTALL_GROUP=staff
    export INSTALL_MODE_FLAG=u+w,go-w,a+rX
    export INSTALL_OWNER=changjoopark
    export INSTALL_ROOT=/tmp/ios-test.dst
    export IPHONEOS_DEPLOYMENT_TARGET=5.1.1
    export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES=YES
    export JAVA_ARCHIVE_TYPE=JAR
    export JAVA_COMPILER=/usr/bin/javac
    export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
    export JAVA_JAR_FLAGS=cv
    export JAVA_SOURCE_SUBDIR=.
    export JAVA_USE_DEPENDENCIES=YES
    export JAVA_ZIP_FLAGS=-urg
    export KEEP_PRIVATE_EXTERNS=NO
    export LD_DEPENDENCY_INFO_FILE=//_dependency_info.dat
    export LD_GENERATE_MAP_FILE=NO
    export LD_MAP_FILE_PATH="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build/-LinkMap--.txt"
    export LD_NO_PIE=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
    export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LIBRARY_FLAG_NOSPACE=YES
    export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
    export LINKER_DISPLAYS_MANGLED_NAMES=NO
    export LINK_WITH_STANDARD_LIBRARIES=YES
    export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
    export LOCAL_APPS_DIR=/Applications
    export LOCAL_DEVELOPER_DIR=/Library/Developer
    export LOCAL_LIBRARY_DIR=/Library
    export MAC_OS_X_PRODUCT_BUILD_VERSION=15F34
    export MAC_OS_X_VERSION_ACTUAL=101105
    export MAC_OS_X_VERSION_MAJOR=101100
    export MAC_OS_X_VERSION_MINOR=1105
    export OBJECT_FILE_DIR="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build/Objects"
    export OBJROOT=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build
    export ONLY_ACTIVE_ARCH=NO
    export OS=MACOS
    export OTHER_CFLAGS=-DNS_BLOCK_ASSERTIONS=1
    export OTHER_CPLUSPLUSFLAGS=-DNS_BLOCK_ASSERTIONS=1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/changjoopark/.rvm/gems/ruby-2.3.1/bin:/Users/changjoopark/.rvm/gems/ruby-2.3.1@global/bin:/Users/changjoopark/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/changjoopark/.rvm/bin"
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
    export PLATFORM_NAME=iphonesimulator
    export PLIST_FILE_OUTPUT_FORMAT=binary
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
    export PRECOMP_DESTINATION_DIR="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build/PrefixHeaders"
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
    export PRODUCT_NAME=
    export PROFILING_CODE=NO
    export PROJECT=ios-test
    export PROJECT_DERIVED_FILE_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/DerivedSources
    export PROJECT_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios
    export PROJECT_FILE_PATH=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/ios-test.xcodeproj
    export PROJECT_NAME=ios-test
    export PROJECT_TEMP_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build
    export PROJECT_TEMP_ROOT=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build
    export REMOVE_CVS_FROM_RESOURCES=YES
    export REMOVE_GIT_FROM_RESOURCES=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
    export REMOVE_HG_FROM_RESOURCES=YES
    export REMOVE_SVN_FROM_RESOURCES=YES
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk
    export SEPARATE_STRIP=NO
    export SEPARATE_SYMBOL_EDIT=NO
    export SHARED_DERIVED_FILE_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/Release-iphonesimulator/DerivedSources
    export SHARED_PRECOMPS_DIR=/var/folders/y5/t02hbcbx1zb5jxtjksg082200000gn/C/com.apple.DeveloperTools/7.3.1-7D1014/Xcode/SharedPrecompiledHeaders
    export SKIP_INSTALL=YES
    export SOURCE_ROOT=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios
    export SRCROOT=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios
    export STRINGS_FILE_OUTPUT_ENCODING=binary
    export STRIP_BITCODE_FROM_COPIED_FILES=NO
    export STRIP_INSTALLED_PRODUCT=YES
    export STRIP_STYLE=all
    export SUPPORTED_PLATFORMS="iphonesimulator iphoneos"
    export SUPPORTS_TEXT_BASED_API=NO
    export SYMROOT=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build
    export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
    export SYSTEM_APPS_DIR=/Applications
    export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
    export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
    export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
    export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR=/System/Library
    export TAPI_VERIFY_MODE=ErrorsOnly
    export TARGETED_DEVICE_FAMILY=1,2
    export TARGETNAME="Build Haxe"
    export TARGET_BUILD_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/Release-iphonesimulator
    export TARGET_NAME="Build Haxe"
    export TARGET_TEMP_DIR="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build"
    export TEMP_DIR="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build"
    export TEMP_FILES_DIR=
    export TEMP_FILE_DIR="/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/ios-test.build/Release-iphonesimulator/Build Haxe.build"
    export TEMP_ROOT=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build
    export TOOLCHAINS=com.apple.dt.toolchain.iOS9_3
    export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
    export UID=501
    export USER=changjoopark
    export USER_APPS_DIR=/Users/changjoopark/Applications
    export USER_LIBRARY_DIR=/Users/changjoopark/Library
    export USE_HEADERMAP=YES
    export VALIDATE_PRODUCT=YES
    export VALID_ARCHS="armv7 arm64 i386"
    export WATCH_BUILT_PRODUCTS_DIR=/Users/changjoopark/Developments/HaxeFlixel/ios-test/export/ios/build/Release-watchsimulator
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=7D1014
    export XCODE_VERSION_ACTUAL=0731
    export XCODE_VERSION_MAJOR=0700
    export XCODE_VERSION_MINOR=0730
    export ZERO_LINK=NO
    export arch=i386
    export diagnostic_message_length=111
    export variant=normal
    /Applications/Xcode.app/Contents/Developer/usr/bin/make
Haxe simulator build: Release-iphonesim
haxe Build.hxml -D simulator -cpp build/Release-iphonesim
cd build/Release-iphonesim; export HXCPP_NO_COLOR=1; haxelib run hxcpp Build.xml -Dios -Diphone -Dsimulator -DHXCPP_CPP11  -DHXCPP_CLANG -DOBJC_ARC `cat Options.txt | while read LINE; do printf " -D$LINE"; done`
Error: Could not find build target "by"
make: *** [build-haxe-i386] Error 1
Command /Applications/Xcode.app/Contents/Developer/usr/bin/make failed with exit code 2

** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution Build\ Haxe
(1 failure)
```
________________________________

**Observed behavior:**
**Expected behavior:**
Run iOS simulator with empty haxeflixel project.

**Comment by Gama11** [comment]
Can you reproduce this with an empty OpenFL project as well?

**Comment by Gama11** [comment]
ping

**Comment by ChangJoo-Park** [comment]
@Gama11 thanks Gama11, I'll try with -Dlegacy.

**Comment by jeichelbaum** [comment]
experiencing the same issue, did you solve it?

**Comment by Tiago-Ling** [comment]
Solution / workaround:

Build the game with the following command:
`lime test ios -Dsource-header=0`

This works with next (OpenFL 3.6.1 + Lime 2.9.1 + HaxeFlixel 4.1.0 + Hxcpp 3.2.205)

**Comment by jeichelbaum** [comment]
setting the var  IPHONE_VER to 9.3 helped me in my case

**Comment by JefePapaya** [comment]
Ok, I didn't get how to set the IPHONE_VER to 9.3 as stated above, so I went looking on the hxcpp and lime folders. It's actually as simple as adding `-DIPHONE_VER=9.3`
Well, finally what did the deal was:
`lime test ios -Dsource-header=0 -DIPHONE_VER=9.3`

Thanks everyone!

**Comment by JefePapaya** [comment]
I would still like to know where those things are defined, so we can have a fix.

**Comment by ibilon** [comment]
@JefePapaya The iphone_ver is in a hxcpp config file (can't remember which one).
Was fixed but hxcpp isn't often released on haxelib.

**Comment by JefePapaya** [comment]
Thanks for the reply @ibilon. I just downloaded the hxcpp current version from master branch.
I've compiled and used it to build for iOS and I still get the same error.
Was there an issue created on hxcpp repository? If so, could you write the link?

**Comment by Gama11** [comment]
I think this is the hxcpp commit that is supposed to fix it: https://github.com/HaxeFoundation/hxcpp/commit/7707d6ba51b1a72c5e9264510d17bd33750e49d9

You still had issues though @JefePapaya?

**Comment by JefePapaya** [comment]
It solves the wrong `IPHONE_VER`, but gives the same error in the first post if I only use `lime test ios`.

If i use `lime teset ios -Dsource-header=0` then it goes further on the build process, but ultimately fail:
```Error: While running :xcrun --sdk iphoneos clang++ -I/Users/papaya/Dev/Games/RepelBall/export/ios/RepelBall/haxe/build/Release-iphoneos-v7/obj/iphoneos-c11-v7/__pch/runtime -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H -c -stdlib=libc++ -O2 -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=5.0 -fobjc-arc -DOBJC_ARC -DENABLE_BITCODE=YES -fembed-bitcode -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-bool-conversion -fno-stack-protector -DIPHONE=IPHONE -DIPHONEOS=IPHONEOS -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -I/usr/local/lib/haxelib/hxcpp/git/include -fmodules -fcxx-modules -fexceptions -fstrict-aliasing -x c++ -Wno-invalid-offsetof /usr/local/lib/haxelib/hxcpp/git/src/hx/Date.cpp -o/Users/papaya/Dev/Games/RepelBall/export/ios/RepelBall/haxe/build/Release-iphoneos-v7/obj/iphoneos-c11-v7/dd18a43b_Date.o
While building module 'QuartzCore' imported from /usr/local/lib/haxelib/hxcpp/git/src/hx/Date.cpp:35:
While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMediaTiming.h:8:
In file included from <module-includes>:2:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:436:1: error: expected unqualified-id
@class NSString, Protocol;
Error: While running :xcrun --sdk iphoneos clang++ -I/Users/papaya/Dev/Games/RepelBall/export/ios/RepelBall/haxe/build/Release-iphoneos-v7/obj/iphoneos-c11-v7/__pch/runtime -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H -c -stdlib=libc++ -O2 -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=5.0 -fobjc-arc -DOBJC_ARC -DENABLE_BITCODE=YES -fembed-bitcode -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-bool-conversion -fno-stack-protector -DIPHONE=IPHONE -DIPHONEOS=IPHONEOS -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -I/usr/local/lib/haxelib/hxcpp/git/include -fmodules -fcxx-modules -fexceptions -fstrict-aliasing -x c++ -Wno-invalid-offsetof /usr/local/lib/haxelib/hxcpp/git/src/hx/Date.cpp -o/Users/papaya/Dev/Games/RepelBall/export/ios/RepelBall/haxe/build/Release-iphoneos-v7/obj/iphoneos-c11-v7/dd18a43b_Date.o
While building module 'QuartzCore' imported from /usr/local/lib/haxelib/hxcpp/git/src/hx/Date.cpp:35:
While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMediaTiming.h:8:
In file included from <module-includes>:2:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:436:1: error: expected unqualified-id
@class NSString, Protocol;
```
then it goes on with more errors of the kind

**Comment by Gama11** [comment]
I see. Can you report that on the hxcpp repo?

**Comment by JefePapaya** [comment]
Sure thing!
As a matter of fact, I just did: https://github.com/HaxeFoundation/hxcpp/issues/504
